### ISSUE TITLE
Medical Dataset

### ISSUE THREAD

**Issue by hhroberthdaniel** [uf-hobi-informatics-lab/GatorTron#2]
Hi, do you plan on releasing the dataset that you have built that includes all medical knowledge?

**Comment by HygeiaOrg** [comment]
Not sure which project you referring to, but all projects are open-sourced from publicly available data.

**Comment by bugface** [comment]
@hhroberthdaniel The downstream tasks datasets are all publicly available.  The corpora used for pretraining contained the pile, MIMIC-III and clinical notes from UF Health. While the pile and mimic are publicly available, we will not release clinical text from UF Health due to IRB/HIPAA. But you can access the pretrained gatortron model from Nvidia NGC.

**Comment by metemadi** [comment]
thank you for providing this excellent work to the open source community. quick question - while it appears that the 345M parameter model is up on NGC, I can't seem to find the larger pretrained models? Are these available to the community? a huge thank you again!!

**Comment by yonghuiwuf** [comment]
GatorTron models are available from Hugging Face: https://huggingface.co/UFNLP

'How to use' codes was added to this repository as well as the Hugging Face repository.
